# Nome do site que aparece no topo
site_name: Página Pessoal - Vitor Domeniquelli Chagas

# Tema que vamos usar
theme:
  name: material
  palette:
    # Esquema de cores (pode ser 'default' para claro ou 'slate' para escuro)
    scheme: slate
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs # Adiciona navegação por abas

# Configuração do menu de navegação
nav:
  - 'Início': 'index.md'
  - 'Projetos':
    - 'Detector de Vagas': 'projetos/detector-de-vagas.md'
    - 'Braço Robótico com ROS': 'projetos/braco-robotico-ros.md'
